

------------------------  LOGIN  ------------------------

CREATE LOGIN [USER] 
	WITH PASSWORD= 'USER', 
    DEFAULT_DATABASE = CP_TEST, 
    DEFAULT_LANGUAGE = [русский], 
    CHECK_EXPIRATION = OFF, 
    CHECK_POLICY = OFF
GO

CREATE LOGIN [ADMIN] 
    WITH PASSWORD= 'ADMIN', 
    DEFAULT_DATABASE = CP_TEST, 
    DEFAULT_LANGUAGE = [русский], 
    CHECK_EXPIRATION = OFF, 
    CHECK_POLICY = OFF
GO

CREATE LOGIN [PROVIDER] 
    WITH PASSWORD= 'PROVIDER', 
    DEFAULT_DATABASE = CP_TEST, 
    DEFAULT_LANGUAGE = [русский], 
    CHECK_EXPIRATION = OFF, 
    CHECK_POLICY = OFF
GO



------------------------  USERS  ------------------------

USE CP_TEST;
CREATE USER [USER] FOR LOGIN [USER] WITH DEFAULT_SCHEMA = [dbo]
ALTER ROLE [db_datareader] ADD MEMBER [USER];
GO

CREATE USER [ADMIN] FOR LOGIN [ADMIN] WITH DEFAULT_SCHEMA = [dbo]
ALTER ROLE [db_datareader] ADD MEMBER [ADMIN];
GO

CREATE USER [PROVIDER] FOR LOGIN [PROVIDER] WITH DEFAULT_SCHEMA = [dbo]
ALTER ROLE [db_datareader] ADD MEMBER [PROVIDER];
GO



------------------------  GRANTS  ------------------------

GRANT EXECUTE ON checkIfOrdersHasBeenCompleted TO [USER];
GRANT EXECUTE ON getOrderStatus TO [USER];
GRANT EXECUTE ON getUserOrdersFromCart TO [USER];
GRANT EXECUTE ON payForAnOrder TO [USER];
GRANT EXECUTE ON placeAnOrder TO [USER];
GRANT EXECUTE ON recordSong TO [USER];
GRANT EXECUTE ON searchTask TO [USER];
GRANT EXECUTE ON signInUser TO [USER];
GRANT EXECUTE ON signUpUser TO [USER];
GRANT SELECT  ON UsersOrders TO [USER];
DENY  SELECT  ON ProvidersTasks TO [USER];

GRANT EXECUTE ON addSongToAlbum TO [PROVIDER];
GRANT EXECUTE ON confirmOrder TO [PROVIDER];
GRANT EXECUTE ON createAlbum TO [PROVIDER];
GRANT EXECUTE ON getProvidersTasks TO [PROVIDER];
GRANT EXECUTE ON signInProvider TO [PROVIDER];
GRANT EXECUTE ON signUpProvider TO [PROVIDER];
GRANT SELECT  ON ProvidersTasks TO [PROVIDER];
DENY  SELECT  ON UsersOrders TO [PROVIDER];

GRANT EXECUTE ON exportUsersXML TO [ADMIN];
GRANT EXECUTE ON importUsersXML TO [ADMIN];
GRANT EXECUTE ON checkIfOrdersHasBeenCompleted TO [ADMIN];
GRANT EXECUTE ON getOrderStatus TO [ADMIN];
GRANT EXECUTE ON searchTask TO [ADMIN];
GRANT EXECUTE ON addSongToAlbum TO [ADMIN];
GRANT EXECUTE ON createAlbum TO [ADMIN];
GRANT EXECUTE ON getProvidersTasks TO [ADMIN];
GRANT EXECUTE ON RandomString TO [ADMIN];
GRANT EXECUTE ON insertCycleStatus TO [ADMIN];
GRANT SELECT  ON UsersOrders TO [ADMIN];
GRANT SELECT  ON ProvidersTasks TO [ADMIN];